#!/bin/bash
#list folder
ls -l /app/
#create file in root
mkdir ~/.llmstack/
ls -l ~/.llmstack/
#copy config file
mv /app/config ~/.llmstack/config
#start initial setup llmstack
/usr/local/bin/llmstack